# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :centos_node do |node|
    node.vm.box = "centos64"
    node.vm.network :private_network, ip: "192.168.56.101"
    node.vm.network "public_network", :bridge => "eth4", ip:"192.168.131.100", :auto_config => "false", :netmask => "255.255.255.0"
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", "centos_ejemplo2" ]
    end
  end
end
