# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :centos_web do |wb|
    wb.vm.box = "centos64_updated4"
    wb.vm.network :private_network, ip: "192.168.56.101"
    wb.vm.network "public_network", :bridge => "eth4", ip:"192.168.131.100", :auto_config => "false", :netmask => "255.255.255.0"
    wb.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_web" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "mirror"
      chef.add_recipe "apache"
      chef.json ={"aptmirror" => {"server" => "192.168.131.254"}}    
    end
  end
  config.vm.define :centos_database do |db|
    db.vm.box = "centos64_updated4"
    db.vm.network :private_network, ip: "192.168.56.102"
    db.vm.network "public_network", :bridge => "eth4", ip:"192.168.131.101", :auto_config => "false", :netmask => "255.255.255.0"
    db.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_database" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "mirror"
      chef.add_recipe "mysql"
      chef.json ={"aptmirror" => {"server" => "192.168.131.254"}}    
    end
  end
end
